name: script1000のデータ屋
description: jsやhtmlなどのデータを保管するサイト
url: https://script1000.github.com
repository: https://github.com/script1000/script1000.github.com
timezone: Japan
google_site_verification: t55QGjwh_eXNPM4WHHhJEAD22F6WhazVlOj_f5naJ5E
plugins:
- jekyll-avatar
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

show_dir_listing: true
theme: jekyll-theme-cayman